[project]
name = "apis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # Versions are kept in sync with requirements.txt
    "fastapi==0.104.1",
    "uvicorn[standard]==0.24.0",
    "httpx==0.24.1",
]
