// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const AdminPanel = lazy(() => import("./pages/AdminPanelSimple.tsx"));
const Company = lazy(() => import("./pages/Company.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const LeadsManagement = lazy(() => import("./pages/LeadsManagement.tsx"));
const Product = lazy(() => import("./pages/Product.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const Search = lazy(() => import("./pages/Search.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/admin", element: <UserGuard><AdminPanel /></UserGuard>},
	{ path: "/company", element: <UserGuard><Company /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/leads", element: <UserGuard><LeadsManagement /></UserGuard>},
	{ path: "/product", element: <UserGuard><Product /></UserGuard>},
	{ path: "/register", element: <UserGuard><Register /></UserGuard>},
	{ path: "/search", element: <UserGuard><Search /></UserGuard>},

];
